name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: "express.js"
        - uses: superfly/flyctl-actions@1.1
          with:
            args: "deploy"
